### ISSUE TITLE
Lodestar-Prater authtication needed

### ISSUE THREAD

**Issue by alexpeterson91** [dappnode/DAppNodePackage-Lodestar-Prater#14]
tracked by https://github.com/dappnode/DAppNodePackage-web3signer-prater/issues/71

Add authentication for validator and web3signer communication

**Comment by dapplion** [comment]
The web3signer requires authentication to **receive** signing calls?

**Comment by alexpeterson91** [comment]
@dapplion im just going off of the web3 signer client selection/handling code we have. I thought there wasn't any needed authentication for lodestar I thought that was something i learned when we did the first round of chiado testing on dappnode a few months ago. But then I thought I'd ask again now as I'm finishing up prepping the client for testing and you mentioned there was a validator <> signer authentication method over discord. Regardless it's relevant since the code for the web3 signer as written currently doesn't allow for no authentication token. It will exit. Not a big deal can just fix that but need to know whether or not it needs to be changed to deal with no auth token or some security parameters like this.
